<?php
/**
 * @file
 * Integrates Commerce Credit Voucher Payment Method with Feeds.
 */

/**
 * Implements hook_feeds_plugins().
 */
function commerce_credit_voucher_import_feeds_plugins() {
  $plugins = array();

  $plugins['FeedsCommerceCreditVoucherProcessor'] = array(
    'name' => 'Commerce Credit Voucher processor',
    'description' => 'Create and update credit vouchers.',
    'help' => 'Create and update credit vouchers from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'FeedsCommerceCreditVoucherProcessor',
      'file' => 'FeedsCommerceCreditVoucherProcessor.inc',
      'path' => drupal_get_path('module', 'commerce_credit_voucher') . '/includes/feeds',
    ),
  );

  return $plugins;
}


/**
 * Implements hook_feeds_importer_default().
 */ 
function commerce_credit_voucher_import_feeds_importer_default() {
  $export = array();

  $feeds_importer = new stdClass();
  $feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
  $feeds_importer->api_version = 1;
  $feeds_importer->id = 'commerce_credit_voucher';
  $feeds_importer->config = array(
    'name' => 'Credit Voucher Importer',
    'description' => 'Imports credit vouchers for Drupal Commerce.',
    'fetcher' => array(
      'plugin_key' => 'FeedsFileFetcher',
      'config' => array(
        'allowed_extensions' => 'csv',
        'direct' => 1,
      ),
    ),
    'parser' => array(
      'plugin_key' => 'FeedsCSVParser',
      'config' => array(
        'delimiter' => ',',
        'no_headers' => 0,
      ),
    ),
    'processor' => array(
      'plugin_key' => 'FeedsCommerceCreditVoucherProcessor',
      'config' => array(
        'mappings' => array(
          0 => array(
            'source' => 'type',
            'target' => 'type',
            'unique' => FALSE,
          ),
          1 => array(
            'source' => 'code',
            'target' => 'code',
            'unique' => 1,
          ),
          2 => array(
            'source' => 'amount',
            'target' => 'amount',
            'unique' => FALSE,
          ),
          3 => array(
            'source' => 'sku',
            'target' => 'sku',
            'unique' => FALSE,
          ),
          4 => array(
            'source' => 'is_active',
            'target' => 'is_active',
            'unique' => FALSE,
          ),
          5 => array(
            'source' => 'start_date',
            'target' => 'start_date',
            'unique' => FALSE,
          ),
          6 => array(
            'source' => 'end_date',
            'target' => 'end_date',
            'unique' => FALSE,
          ),
        ),
        'update_existing' => '2',
        'input_format' => 'plain_text',
      ),
    ),
    'content_type' => '',
    'update' => 0,
    'import_period' => 1800,
    'expire_period' => 3600,
    'import_on_create' => TRUE,
    'process_in_background' => FALSE,
  );

  $export['commerce_credit_voucher'] = $feeds_importer; 

  return $export;
}


/**
 * Implements hook_ctools_plugin_api().
 */ 
function commerce_credit_voucher_import_ctools_plugin_api($module = '', $api = '') {
  if ($module == "feeds" && $api == "feeds_importer_default") {
    // The current API version is 1.
    return array("version" => 1);
  }
}
