<?php
/**
 * @file
 * Provides a UI functionality for the credit voucher payment method module.
 */
 
/**
 * Implements hook_entity_info_alter().
 */
function commerce_credit_voucher_ui_entity_info_alter(&$entity_info) {
  // Add a URI callback to the commerce credit voucher entity.
  $entity_info['commerce_credit_voucher']['uri callback'] = 'commerce_credit_voucher_ui_credit_voucher_uri';
}


/**
 * Entity uri callback: points to the admin view page of the given credit voucher.
 */
function commerce_credit_voucher_ui_credit_voucher_uri($commerce_credit_voucher) {
  // First look for a return value in the default entity uri callback.
  $uri = commerce_credit_voucher_uri($commerce_credit_voucher);

  // If a value was found, return it now.
  if (!empty($uri)) {
    return $uri;
  }

  // Only return a value if the user has permission to view the credit voucher.
  if (commerce_credit_voucher_access('view', $commerce_credit_voucher)) {
    return array(
      'path' => 'admin/commerce/credit-vouchers/' . $commerce_credit_voucher->voucher_id,
    );
  }

  return NULL;
}


/**
 * Implementation of hook_menu().
 */
function commerce_credit_voucher_ui_menu() {
  $items = array();

  // Note: admin/commerce/credit-vouchers is defined by a default View.

  /*
  $items['cost-centre/add'] = array(
    'title' => 'Add new Cost Centre',
    'page callback' => 'cost_centre_add',
    'access arguments' => array('create cost centre content'),
    'weight' => 1,
    'menu_name' => 'management',
    'file' => 'cost_centre.pages.inc',
  );
  $items['cost-centre/%cost_centre'] = array(
    'title callback' => 'cost_centre_page_title',
    'title arguments' => array(1),
    'page callback' => 'cost_centre_page_view',
    'page arguments' => array(1),
    'access arguments' => array('view cost centre content'),
    'file' => 'cost_centre.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['cost-centre/%cost_centre/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['cost-centre/%cost_centre/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'cost_centre_page_edit',
    'page arguments' => array(1),
    'access arguments' => array('edit cost centre content'),
    'weight' => 0,
    'file' => 'cost_centre.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['cost-centre/%cost_centre/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cost_centre_delete_confirm', 1),
    'access arguments' => array('delete cost centre content'),
    'weight' => 1,
    'file' => 'cost_centre.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );
  */

  return $items;
}


/**
 * Implements hook_views_api().
 */
function commerce_credit_voucher_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_credit_voucher') . '/includes/views',
  );
}
